### ISSUE TITLE
Feeds description and data freshness

### ISSUE THREAD

**Issue by Homas** [blocklistproject/Lists#14]
1. Are you going to provide some description of the feeds and how they are generated? 
I do understand that many names are self-explanatory but for example the crypto list what crypto currencies does it includes?
2. I'm considering to use your feeds @ ioc2rpz community web-site (free RPZ feeds) but have concerns regarding how fresh is the data. How often do you update the lists? On github I see that many lists were published 25 days ago including fraud, scam and malware (actually was updated a week ago).

**Comment by blocklistproject** [comment]
1) Yes as we move forward and find some stability using GitHub we will be adding more information regarding the updating and maintenance of the lists. 

2) You are correct that some of our lists are updated more or less frequently than others. As we have come to find out through  trial and error frequency of updated, does not directly coincide with quality. We now update the lists as we find domains that need to be on the lists. Prior to moving to GitHub we had (not exactly but close to) a more update the masses and consequences be damned. This made for a very upset user base but worked when we first started this project because it was just a handful (about 5 of us) using the lists so if we screwed up we could typically fix it fairly quick. We were also missing some false positives because being only 5 of us using it we were not visiting a wide enough range of websites to find all the false positives. 

I hope this helps, or starts to help you understand the lists. If you have more questions, please feel free to keep the conversation going!

**Comment by Homas** [comment]
Yes. Thanks for the information. My main concern that a lot of domains added or expired every day and if the feeds are almost stale this means that they do not provide 100% coverage but may be good for most of the top requested websites e.g. from top 1m.

**Comment by blocklistproject** [comment]
We are working every day to vet URLs to add and/or remove from the lists. Hopefully as more and more people use them they will become less "stale" and more fresh. As the project matures we are learning better and better was to maintain the lists. Any suggestions would be greatly appreciated.

**Comment by Homas** [comment]
Sure. Thanks!  I'll create several RPZ feeds based on your data and take a look at home on them before making them publicly available.

You can also update how the feed can be used by adding my open source tool ioc2rpz https://github.com/Homas/ioc2rpz
In comparing with PiHole, RPZ which is supported on ISC Bind and PowerDNS is an enterprise/ISP grade solution. PiHole mostly for home users.
