### ISSUE TITLE
[Remove Request] - tcnj.co1.qualtrics.com

### ISSUE THREAD

**Issue by smcclosr** [blocklistproject/Lists#329]
URL you wish to be removed:
tcnj.co1.qualtrics.com
co1.qualtrics.com
tcnj.qualtrics.com

Why you believe this to be a false positive:
These are related to getting access to a college, The College of New Jersey; tcnj.edu

List it is on:
ads-nl.txt

Other info you think we should know:
Added these 3 domains to local whitelist, and everything works fine, so believe found all related domains.

**Comment by fishcharlie** [comment]
I'm not completely confident I support this removal. Maybe a migration to the tracking list instead of ads?? But the fact that blocking these domains leads to website incompatibility is not a good enough reason to warrant removal in my opinion. Part of using block lists is that it can cause incompatibility issues with websites.

This issue should really be brought up with The College of New Jersey.

It's a fine line here. Obviously it'd be great if every website was fully compatible with blocklists. The question is how far do we go removing domains that are clearly trackers to allow for website compatibility? I'd argue that removing these domain names will encourage sites to make their websites incompatible if these domains are blocked. Which sets a bad precedent.

**Comment by blocklistproject** [comment]
Tomorrow this will be moved to tracker

**Comment by blocklistproject** [comment]
This was removed and migrated to tracking. Thank you
