### ISSUE TITLE
[Remove Request] - a1.net

### ISSUE THREAD

**Issue by WordsOfMe** [blocklistproject/Lists#350]
URL you wish to be removed: a1.net

Why you believe this to be a false positive: A1 Telekom Austria is the largest ISP and cellphone provider in Austria, with approx. 7 Mio customers.

List it is on: abuse

Other info you think we should know: While I appreciate the work done by the blocklist project team, I personally will stop using these lists hence this is the second false postive of large impact within a very short time (the other was gmail.com, issue #317 ). To me it is not transparent which evidence is used for adding URLs to the lists, and it seems there is neither quality control nor any whitelist in place.

**Comment by blocklistproject** [comment]
This has been fix. Thank you. While we do our best to address any "false positive" in a timely manner we are still human and things are going to slip through the cracks. As to your comment regarding a "whitelist in place", the goal of this project is to provide modular block lists. White list are extremely personalized, what one person wants on their whitelist another person would be very against. I think that we would get more "hate" for trying to create a whitelist than we already do for creating blocklists. LOL 

We are truly sorry to see you go and hope that you are able to find a list that will suite your needs and does not have any false positives. We are working towards that goal everyday and appreciate you trying out our lists! Good luck and happy hunting.

**Comment by WordsOfMe** [comment]
Thank you for your kind and quick reply.
My suggestion would be to put a whitelist in place for false positives that have once been removed - in order to avoid adding them again to any list (like in issues #317 and #92). Also, as mentioned, neither the process of adding entries to the lists is clear to me, nor could I find any information on the project's website. Transparency might increase trust in these lists.
These are just my 2 cents. In any case, thank you for your efforts and dedication.

**Comment by blocklistproject** [comment]
Ok, I see what you mean by whitelist and I think that is a great idea! A list that is hosted on the GitHub repo as more of a final double check to make sure an already removed domain isn't readded. I think this is an amazing idea. Let me look more into how to do this. @fishcharlie is an automaton wizard, wonder if this could be done with automation?

**Comment by fishcharlie** [comment]
> @fishcharlie is an automaton wizard, wonder if this could be done with automation?

@blocklistproject Yes. I can start work on this. However, this one will be one of the most complicated ones we've done so far. Many edge cases and things to think about here. I'll be sure to add some extra detail to the PR comment so we can discuss and ensure it's the best way to do it.

Might be a little bit before I get around to this tho.

---

> While I appreciate the work done by the blocklist project team, I personally will stop using these lists hence this is the second false postive of large impact within a very short time (the other was gmail.com, issue #317 ). To me it is not transparent which evidence is used for adding URLs to the lists, and it seems there is neither quality control nor any whitelist in place

@WordsOfMe As someone who experienced a lot of false positives when I started using these lists, I can speak to this from a slightly different perspective than @blocklistproject.

Striving for accuracy and completeness is critical with a project like this. It hasn't always met the mark. You can find issues I have created with false positives. This is why I have tried to become more involved in automation and helping this project stay sustainable. Although it's still the early stages of that effort, I believe it has already lead to a significant improvement in list quality for the project.

The more a project like this scales, the more difficult it becomes to ensure a high level of quality manually. I will continue to help where I can to ensure the project meets these goals.

However, no list is completely accurate. You should have a system in place to temporarily bypass your blocklists when necessary. And continue to raise issues on this repo so they can be fixed. This should truly be a community effort to make it better. All of this data is under the Unlicense which is very permissive (a huge benefit in my opinion). The more support this project gets from the community, the better this project will be.

@blocklistproject deserves a **LOT** of credit for maintaining this project and being so responsive to these issues. This issue was solved in less than 3 hours. I don't think you are going to find a project with that level of responsiveness. And I think that is a critical benefit that you won't find on other lists.

Finally. In terms of transparency and quality control. A large amount of domains that are false positives have existed throughout the life of the project. Although not all, most have. As @blocklistproject mentioned in this comment https://github.com/blocklistproject/Lists/discussions/251#discussioncomment-574722, these lists were created from an aggregate of other lists along with scraping from other sources. To me, that is **HIGHLY** transparent. Did that lead to a lot of false positives? Looks like it. Was that the correct decision to jump start this project? Personally, I think that was hands down the correct decision. It got a lot of content to bootstrap the project.

In my opinion, this project is setup for **AMAZING** success in the future like it never has before.

I hope you will reconsider sticking with the project and continuing to play a role in coming up with ideas like your whitelist idea and reporting false positives, or at the very least continue to monitor the project for potential future use.
