### ISSUE TITLE
possibility to create a full host and adguard?

### ISSUE THREAD

**Issue by gallegonovato** [blocklistproject/Lists#533]
Good afternoon:

First of all apologize if I do something wrong. But it is not my intention at all to do so.

Secondly thank you for all your wonderful work. And for your wonderful lists of hosts and adguard.

I would like to ask if it would be possible to merge all hosts and adguard
into one for better protection and to be able to use it for example in adaway on mobile (the hosts). And in ublock the adguard , without having to put one by one their lists.

Since although it sounds strange my suggestion, comment that of the table https://github.com/blocklistproject/Lists#main-lists because I use them all. Since I am worried about the security of all the subjects that treat their lists. As well as those of the table https://github.com/blocklistproject/Lists#beta-lists

Except that Adaway I do not use the list of 
  Smart TV as it is a mobile phone. But for example that of WhatsApp I also use it. Since although I do not use this application I am tired of seeing that visiting some web, connections to this come out.

So if it would be possible to unite all your hosts and Adguard in a single host and Adguard (a single hosts file and a single Adguard file). Well, I would be very grateful to you, and like me, many other people.

Thank you very much for your time and help

Best regards

**Comment by gallegonovato** [comment]
Good afternoon @iam-py-test

Sorry for taking so long to get back to you. But I was busy at work and didn't have time earlier.

Thank you for your help and for all your work and time.

The hosts are running on Adaway with no problems. And your adguard lists are working perfectly in ublock origin.

Just thank you for your time and help.

**Comment by fishcharlie** [comment]
> My understanding is that the everything list is all of the other lists combined

@iam-py-test is (*basically*) correct here. You can view the code for how the everything list gets generated [here](https://github.com/blocklistproject/Lists/blob/master/scripts/create-everything-list.js).

The important part is that there is a hardcoded array of lists to include. So new lists must be added to that array in order to get included in the everything list.

As you can see as well, some beta lists are not included in the everything list.

But, by and large, it's all the other lists combined.

---

@gallegonovato It looks like your question is answered tho and this issue has been inactive for some time so I'm going to close this issue as resolved for now. Feel free to create another issue if you need more help.
